### ISSUE TITLE
The popup menu of profile button Edge is being forcefully dismissed

### ISSUE THREAD

**Issue by skyline75489** [McYoloSwagHam/win3wm#10]
Even if the current Edge window has focus, the profile popup will be forcefully dismissed by win3wm.

![image](https://user-images.githubusercontent.com/4710575/109784848-73f62c00-7c46-11eb-97a9-ebef71da4df3.png)

**Comment by McYoloSwagHam** [comment]
So essentially what's going on here is that WinWM has a watchdog that makes sure that the focus bar (default yellow) is on the correct window and it also tells windows to force the focus for that window, the way edge responds is that whenever you click on the personal thing it checks if you still have focus, because WinWM is moving focus to the actual Edge window, the personal window closes.

A way you can mitigate this is by going fullscreen (mod+f), because the behavior of WinWM while you're watching a fullscreen  video or something of the sort is to not show the focus bar. 

I could add in an option for the focus bar to just render instead of forcing focus on the window.

**Comment by skyline75489** [comment]
“Going fullscreen" is actually a pretty good solution. Thanks for such a wonderful tool 🎉

**Comment by ChristopherL-STCU** [comment]
I do like the option to just render though, or for the rendering to follow the window in focus

**Comment by OlympusMonds** [comment]
Just as a note, I had this happen with Chrome or Firefox extensions too.

**Comment by McYoloSwagHam** [comment]
added force_focus option in newest commit e50cf7f38da0221ede99e1148ebd8d19397b1ed3
