### ISSUE TITLE
Virus Alert 

### ISSUE THREAD

**Issue by gambit823** [McYoloSwagHam/win3wm#14]
1. Downloaded WinWm.zip from https://github.com/McYoloSwagHam/win3wm/releases/download/v1.0.4/WinWM.zip
2. Extracted to C:\Program Files (x86)\WinWM
3. Ran WinWM.exe
4. Windows 10 threw a virus alert:
Trojan:Win32/Wacatac.B!ml
 file: C:\Program Files (x86)\WinWM\x86ipc.exe

**Comment by McYoloSwagHam** [comment]
Hi, in the documentation in the FAQ it's listed


Q: Anti-virus flags WinWM software as malware, or disables it
A: WinWM injects code into every window that it controls, to regulate window behaviour, this can flag anti-viruses, because some malware will attempt to inject itself into many processes to hide itself. Anti-viruses cannot tell the difference.
