### ISSUE TITLE
[Feature request] Sync focus with keyboard focus

### ISSUE THREAD

**Issue by Picoseconds** [McYoloSwagHam/win3wm#25]
I find that the current focus system is kind of odd because I need to click on the window AND focus win3wm because they are not the same, could you add some kind of synchronization to the actual window focus?

**Comment by Picoseconds** [comment]
Kind of like a two-way version of force_focus

**Comment by McYoloSwagHam** [comment]
Yeah this is one of the boxes in the TODOs section,  but there is a hotkey that will focus on the current window your mouse is on it is mod+q. 

https://mcyoloswagham.github.io/win3wm/hotkeys.html#focus_mouse

I want to make it automatic but it's problematic because I'm just not sure how to properly detect mouse leaving/entering, without doing some hacky shit and at the moment I'm pretty busy

**Comment by McYoloSwagHam** [comment]
Added in a09feb74b46bbf53fc979c67a93aeac6ec531b30
